ghc-options:
  -threaded -rtsopts -with-rtsopts=-N
name: linklater-examples
name:
  linklater-examples
version:
  4.0.0.0
category:
  Web
dependencies:
  HTTP
  , aeson
  , base < 5
  , base-prelude
  , bytestring
  , jpg-to
  , lens
  , lens-aeson
  , linklater
  , mtl
  , network
  , pcre-heavy
  , random-shuffle
  , text
  , uri-bytestring
  , warp
  , websockets
  , wreq
  , wuss
executables:
  streambot:
    main: Main.hs
    source-dirs: app
